### ISSUE TITLE
これはウンボ！

### ISSUE THREAD

**Issue by Notobato** [EmiRemi0580/Typing-SuiSui-Game#1]
ウンボタイザー
これはなかなか面白いゲームです
タイピングのヴァリエーションを増やしてください

**Comment by EmiRemi0580** [comment]
嫌です
面倒くさい

**Comment by Notobato** [comment]
わたしが勝手に増やします!

**Comment by EmiRemi0580** [comment]
oh no
許可します

**Comment by Notobato** [comment]
てめーのコード、フォークしてやったからな！

**Comment by Notobato** [comment]
仏説摩訶般若波羅蜜多心経
観自在菩薩行深般若波羅蜜多時照見五蘊皆空度一切苦厄舎利子色不異空空不異色色即是空空即是色受想行識亦復如是舎利子是諸法空相不生不滅不垢不浄不増不減是故空中無色無受想行識無眼耳鼻舌身意、無色声香味触法無眼界乃至無意識界無無明亦無無明尽乃至無老死亦無老死尽無苦集滅道無智亦無得以無所得故菩提薩埵依般若波羅蜜多故心無罣礙無罣礙故無有恐怖遠離一切顛倒夢想究竟涅槃三世諸仏依般若波羅蜜多故得阿耨多羅三藐三菩提故知般若波羅蜜多是大神呪是大明呪是無上呪是無等等呪能除一切苦真実不虚故説般若波羅蜜多呪
即説呪曰羯諦羯諦波羅羯諦波羅僧羯諦菩提薩婆訶
般若心経

**Comment by remu622** [comment]
ee

**Comment by remu622** [comment]
ブッダ

**Comment by EmiRemi0580** [comment]
仏説。

**Comment by Notobato** [comment]
これはひどいね

**Comment by EmiRemi0580** [comment]
ここは２ちゃんねるではないです

**Comment by remu622** [comment]
public class Main {
    public static void main(String[] args) {
        System.out.printin("Hello world");
    }
}


これ実行されないぞ...どうしてだ
